import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import { getMessaging, getToken, isSupported, onMessage } from "firebase/messaging";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { auth, db } from "../lib/firebase";

export default function ExpenseReminders({user}:{user:User}) {
 const [serverReady,setServerReady]=useState(false),[supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[skip,setSkip]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const publicKey=import.meta.env.VITE_FIREBASE_VAPID_KEY as string|undefined;
 const deviceKey=`expense-push-device-${user.uid}`;
 const deviceId=()=>{let value=localStorage.getItem(deviceKey);if(!value){value=crypto.randomUUID().replace(/-/g,"");localStorage.setItem(deviceKey,value);}return value;};
 useEffect(()=>{let current=true;void fetch("/api/expense-reminders?status=1").then(r=>r.json()).then(result=>{if(current)setServerReady(Boolean(result.ready));}).catch(()=>{});void isSupported().then(value=>{if(current)setSupported(value);}).catch(()=>{});if(db)void getDoc(doc(db,"subscribers",user.uid)).then(snapshot=>{if(!current)return;const id=localStorage.getItem(deviceKey);const saved=id?snapshot.data()?.expensePushDevices?.[id]:null;setEnabled(Boolean(saved?.enabled));setSkip(saved?.skipIfAdded!==false);}).catch(()=>{if(current)setMessage("We couldn’t load your reminder preferences. Refresh the page to try again.");});return()=>{current=false;};},[user.uid,deviceKey]);
 useEffect(()=>{if(!supported || !auth)return;return onMessage(getMessaging(auth!.app),payload=>{void navigator.serviceWorker.getRegistration("/expenses").then(reg=>reg?.showNotification(payload.data?.title||"Expense reminder",{body:payload.data?.body||"Take a minute to add today’s expenses.",tag:"expense-daily-reminder",data:{url:"/expenses?add=1"},icon:"/profile-avatar.png"}));});},[supported,user]);
 const save=async(value:boolean,token?:string)=>{if(!db)throw Error("Your preferences couldn’t be saved. Please try again.");await setDoc(doc(db,"subscribers",user.uid),{expensePushEnabled:true,expensePushDevices:{[deviceId()]:{enabled:value,skipIfAdded:skip,...(token?{token}:{}),updatedAt:new Date().toISOString()}}},{merge:true});setEnabled(value);};
 const enable=async()=>{setBusy(true);setMessage("");try{if(!publicKey)throw Error("Reminders are temporarily unavailable. Please try again later.");const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Notifications are not allowed. You can enable them in your browser’s site settings.");const config=encodeURIComponent(JSON.stringify(auth!.app.options));const registration=await navigator.serviceWorker.register(`/expense-push-sw.js?config=${config}`,{scope:"/expenses"});if(!registration.active)await new Promise<void>((resolve,reject)=>{const worker=registration.installing||registration.waiting;const timeout=setTimeout(()=>reject(Error("Notification setup timed out. Please try again.")),15000);const check=()=>{if(worker?.state==="activated"){clearTimeout(timeout);resolve();}else if(worker?.state==="redundant"){clearTimeout(timeout);reject(Error("Notifications couldn’t be enabled. Please try again."));}};worker?.addEventListener("statechange",check);check();});const token=await getToken(getMessaging(auth!.app),{vapidKey:publicKey,serviceWorkerRegistration:registration});await save(true,token);setMessage("Daily reminders are on for this device.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to enable notifications.");}finally{setBusy(false);}};
 const turnOff=async()=>{setBusy(true);try{await save(false);setMessage("Daily reminders are off on this device.");}catch{setMessage("Unable to turn off reminders. Please try again.");}finally{setBusy(false);}};
 const test=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/expense-reminders",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({deviceId:deviceId()})});const payload=await response.json();if(!response.ok)throw Error(payload.error||"We couldn’t send the preview. Please try again.");setMessage("Reminder preview sent. Check your notifications.");}catch(error){setMessage(error instanceof Error?error.message:"We couldn’t send the preview. Please try again.");}finally{setBusy(false);}};
 return <details className="expense-reminders"><summary>Daily reminders <span>{enabled?"On":"Off"}</span></summary><div><p>A small reminder to keep your spending up to date.</p><div className="expense-reminder-schedule"><span>Every evening</span><strong>9–10 PM <small>India time</small></strong></div><label><input type="checkbox" checked={skip} disabled={enabled||busy} onChange={e=>setSkip(e.target.checked)}/> Only remind me if I haven’t added an expense today</label><details className="expense-reminder-help"><summary>About reminders</summary><p>Reminders are enabled separately on each device. Arrival time can vary with browser and device settings.</p><p>On iPhone or iPad, add the tracker to your Home Screen and open it there to turn on reminders.</p></details>{(!publicKey||!serverReady)&&<p role="status">Reminders are temporarily unavailable. Please try again later.</p>}{!supported&&<p role="status">This browser doesn’t support reminders. Try another browser or open the tracker from your Home Screen.</p>}<div className="expense-reminder-actions">{enabled?<><button type="button" className="expense-button expense-button-secondary" disabled={busy||!serverReady||!supported} onClick={()=>void test()}>Preview reminder</button><button type="button" className="expense-button expense-button-secondary" disabled={busy} onClick={()=>void turnOff()}>Turn off reminders</button></>:<button type="button" className="expense-button expense-button-primary" disabled={busy||!publicKey||!serverReady||!supported} onClick={()=>void enable()}>{busy?"Enabling…":"Turn on reminders"}</button>}</div>{enabled&&<small>To change this preference, turn reminders off and back on.</small>}{message&&<p role="status">{message}</p>}</div></details>;
}

