import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import { getMessaging, getToken, isSupported, onMessage } from "firebase/messaging";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { auth, db } from "../lib/firebase";

export default function ExpenseReminders({user}:{user:User}) {
 const [serverReady,setServerReady]=useState(false),[supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[skip,setSkip]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const publicKey=import.meta.env.VITE_FIREBASE_VAPID_KEY as string|undefined;
 const deviceKey=`expense-push-device-${user.uid}`;
 const deviceId=()=>{let value=localStorage.getItem(deviceKey);if(!value){value=crypto.randomUUID().replace(/-/g,"");localStorage.setItem(deviceKey,value);}return value;};
 useEffect(()=>{let current=true;void fetch("/api/expense-reminders?status=1").then(r=>r.json()).then(result=>{if(current)setServerReady(Boolean(result.ready));}).catch(()=>{});void isSupported().then(value=>{if(current)setSupported(value);}).catch(()=>{});if(db)void getDoc(doc(db,"subscribers",user.uid)).then(snapshot=>{if(!current)return;const id=localStorage.getItem(deviceKey);const saved=id?snapshot.data()?.expensePushDevices?.[id]:null;setEnabled(Boolean(saved?.enabled));setSkip(saved?.skipIfAdded!==false);}).catch(()=>{if(current)setMessage("Unable to read reminder settings. Check your account access and try again.");});return()=>{current=false;};},[user.uid,deviceKey]);
 useEffect(()=>{if(!supported || !auth)return;return onMessage(getMessaging(auth!.app),payload=>{void navigator.serviceWorker.getRegistration("/expenses").then(reg=>reg?.showNotification(payload.data?.title||"Expense reminder",{body:payload.data?.body||"Take a minute to add today’s expenses.",tag:"expense-daily-reminder",data:{url:"/expenses?add=1"},icon:"/profile-avatar.png"}));});},[supported,user]);
 const save=async(value:boolean,token?:string)=>{if(!db)throw Error("Account storage is unavailable.");await setDoc(doc(db,"subscribers",user.uid),{expensePushEnabled:true,expensePushDevices:{[deviceId()]:{enabled:value,skipIfAdded:skip,...(token?{token}:{}),updatedAt:new Date().toISOString()}}},{merge:true});setEnabled(value);};
 const enable=async()=>{setBusy(true);setMessage("");try{if(!publicKey)throw Error("Push notifications need the Firebase Web Push public key configured first.");const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Notifications are not allowed. You can enable them in your browser’s site settings.");const config=encodeURIComponent(JSON.stringify(auth!.app.options));const registration=await navigator.serviceWorker.register(`/expense-push-sw.js?config=${config}`,{scope:"/expenses"});if(!registration.active)await new Promise<void>((resolve,reject)=>{const worker=registration.installing||registration.waiting;const timeout=setTimeout(()=>reject(Error("Notification setup timed out. Please try again.")),15000);const check=()=>{if(worker?.state==="activated"){clearTimeout(timeout);resolve();}else if(worker?.state==="redundant"){clearTimeout(timeout);reject(Error("Notification worker could not start."));}};worker?.addEventListener("statechange",check);check();});const token=await getToken(getMessaging(auth!.app),{vapidKey:publicKey,serviceWorkerRegistration:registration});await save(true,token);setMessage("Enabled on this device. Use Send test to check delivery.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to enable notifications.");}finally{setBusy(false);}};
 const turnOff=async()=>{setBusy(true);try{await save(false);setMessage("Daily reminders are off on this device.");}catch{setMessage("Unable to turn off reminders. Please try again.");}finally{setBusy(false);}};
 const test=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/expense-reminders",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({deviceId:deviceId()})});const payload=await response.json();if(!response.ok)throw Error(payload.error||"Unable to send a test notification.");setMessage("Test sent to the push service. Check your device notifications.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to send test.");}finally{setBusy(false);}};
 return <details className="expense-reminders"><summary>Daily reminders <span>{enabled?"On this device":"Off"}</span></summary><div><p>A gentle nudge to add your expenses, around 9–10 PM India time. Delivery can vary with your browser and device.</p><label><input type="checkbox" checked={skip} disabled={enabled||busy} onChange={e=>setSkip(e.target.checked)}/> Skip if I already added an expense today</label><p className="expense-compare-note">On iPhone or iPad, add this tracker to your Home Screen and open it there to enable notifications.</p>{(!publicKey||!serverReady)&&<p role="status">Push setup is pending. The site owner needs to finish notification setup.</p>}{!supported&&<p role="status">Push notifications are unavailable in this browser. Try a supported browser or the installed Home Screen app.</p>}<div className="expense-reminder-actions">{enabled?<><button type="button" className="expense-button expense-button-secondary" disabled={busy||!serverReady||!supported} onClick={()=>void test()}>Send test</button><button type="button" className="expense-button expense-button-secondary" disabled={busy} onClick={()=>void turnOff()}>Turn off</button></>:<button type="button" className="expense-button expense-button-primary" disabled={busy||!publicKey||!serverReady||!supported} onClick={()=>void enable()}>{busy?"Setting up…":"Enable notifications"}</button>}</div>{enabled&&<small>Turn off to change the skip preference, then enable again.</small>}{message&&<p role="status">{message}</p>}</div></details>;
}

