import { useEffect, useState, type ReactNode } from "react";
import SiteNavigation from "./SiteNavigation";

type RadarStory = { href: string; title: string; source: string; category: string; summary: string; whyItMatters: string; publishedAt?: string; isLive?: boolean };
type RadarViewProps<T extends RadarStory> = { signals: T[]; status: "loading" | "live" | "fallback"; updatedAt: string; onRefresh: () => void; onOpen: (signal: T) => void; renderSave: (signal: T) => ReactNode };
function dateLabel(value?: string) { const date = value ? new Date(value) : null; return date && Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("en", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(date) : "Date unavailable"; }
export default function AiRadarView<T extends RadarStory>({ signals, status, updatedAt, onRefresh, onOpen, renderSave }: RadarViewProps<T>) {
  const [category, setCategory] = useState("All signals");
  const categories = ["All signals", ...Array.from(new Set(signals.map(signal => signal.category)))];
  const visible = category === "All signals" ? signals : signals.filter(signal => signal.category === category);
  const liveCount = signals.filter(signal => signal.isLive).length;
  useEffect(() => { if (category !== "All signals" && !signals.some(signal => signal.category === category)) setCategory("All signals"); }, [signals, category]);
  return <><a className="skip-link" href="#main-content">Skip to AI Radar</a><SiteNavigation minimal fallbackHref="/" />
    <main className="studio-page radar-journal" id="main-content">
      <header className="studio-intro radar-journal-intro"><div><p className="studio-label">A reading list for builders</p><h1>AI Radar<span>.</span></h1><p className="studio-description">AI updates worth your time.<br />Models, tools, and research from trusted sources.</p></div><div className="radar-refresh"><button type="button" onClick={onRefresh} disabled={status === "loading"}><span aria-hidden="true">↻</span>{status === "loading" ? "Refreshing…" : "Refresh feeds"}</button><p role="status">{status === "loading" ? "Checking the sources" : liveCount ? `Updated ${dateLabel(updatedAt)}` : "Official source directory"}</p></div></header>
      <div className="radar-journal-summary"><span><strong>{signals.length}</strong> {liveCount ? "updates & sources" : "sources to explore"}</span><span><strong>{new Set(signals.map(signal=>signal.source)).size}</strong> trusted sources</span><a href="#radar-method">How this feed works <span aria-hidden="true">↗</span></a></div>
      {status !== "loading" && (status === "fallback" || liveCount === 0) && <p className="radar-fallback" role="status">Fresh stories are unavailable right now. Explore the official sources below, or refresh to try again.</p>}
      <section className="radar-journal-library" aria-labelledby="radar-feed-title" id="radar-feed"><div className="radar-filter-heading"><h2 id="radar-feed-title">The reading list</h2><span>{visible.length} {visible.length === 1 ? "item" : "items"}</span></div><div className="radar-journal-filters" role="group" aria-label="Filter AI updates">{categories.map(item=><button type="button" key={item} aria-pressed={category === item} onClick={()=>setCategory(item)}>{item}</button>)}</div>
        <div className="radar-journal-list">{visible.map((signal,index)=><article className="radar-journal-story" key={`${signal.source}-${signal.href}`}><span className="radar-journal-number" aria-hidden="true">{String(index+1).padStart(2,"0")}</span><div><div className="radar-journal-meta"><span>{signal.source}</span><span>{signal.category}</span>{signal.isLive && signal.publishedAt && Number.isFinite(Date.parse(signal.publishedAt)) ? <time dateTime={signal.publishedAt}>{dateLabel(signal.publishedAt)}</time> : <span>{signal.isLive ? "Date unavailable" : "Source directory"}</span>}</div><h3><a href={signal.href} target="_blank" rel="noreferrer" onClick={()=>onOpen(signal)}>{signal.title}</a></h3><p className="radar-journal-description">{signal.summary || signal.whyItMatters}</p><div className="radar-journal-actions"><a className="studio-text-link" href={signal.href} target="_blank" rel="noreferrer" onClick={()=>onOpen(signal)}>{signal.isLive ? "Read original" : "Explore source"} <span aria-hidden="true">↗</span></a><div className="radar-journal-save">{renderSave(signal)}</div></div></div></article>)}</div>
        {!visible.length && <div className="radar-journal-empty"><h3>No updates here yet.</h3><p>Try another category or refresh the sources.</p></div>}
      </section>
      <aside className="radar-journal-method" id="radar-method"><div><p className="studio-label">Read with context</p><h2>Good sources.<br />Your own perspective.</h2></div><div><p>Stories are ranked for recency and relevance to builders, with a mix of sources. Open the original article for the full context.</p><p>When a feed is unavailable, its official source page appears with a “Source directory” label. Save useful stories to revisit them later.</p><a className="studio-text-link" href="/saved-posts">Your saved reading <span aria-hidden="true">↗</span></a></div></aside>
    </main></>;
}
