import SiteNavigation from "./SiteNavigation";

type StartHereViewProps = { articleCount: number; projectCount: number; updates: { href: string; title: string; category: string; date: string; dateLabel: string }[] };
const directory = [
  { title: "The work", note: "Experience and systems built in practice.", links: [["/portfolio", "Portfolio"], ["/projects", "All case studies"], ["/portfolio#experience", "Experience"], ["/portfolio#credentials", "Education & credentials"], ["/about", "About Sai"]] },
  { title: "Ideas & experiments", note: "Learn something. See it put to work.", links: [["/blogs", "Writing"], ["/ai-radar", "AI Radar"], ["/active-builds", "Active Builds"], ["/active-builds/sai-assistant", "Sai’s Assistant"], ["/learn-with-me", "Learn With Me"]] },
  { title: "Your next stop", note: "Keep reading, follow along, or get in touch.", links: [["/saved-posts", "Saved Posts"], ["/shelf", "Sai’s Shelf"], ["/dashboard", "Dashboard"], ["/whats-new", "What’s New"], ["/work-with-me", "Work With Me"]] },
];
export default function StartHereView({ articleCount, projectCount, updates }: StartHereViewProps) {
  return <><a className="skip-link" href="#main-content">Skip to start here</a><SiteNavigation minimal fallbackHref="/" />
    <main className="studio-page wayfinder-page" id="main-content">
      <header className="wayfinder-intro"><div><p className="studio-label">A guide to this site</p><h1>Start here<span>.</span></h1><p className="studio-lead">A few good places<br />to begin.</p><p className="studio-description">I’m Sai. I build backend systems, search platforms, and practical AI applications. Here’s where to find the work and the thinking behind it.</p><div className="wayfinder-facts"><span><strong>{projectCount}</strong> projects</span><span><strong>{articleCount}</strong> engineering notes</span></div></div>
        <nav className="wayfinder-route" aria-label="Suggested first visit"><p className="studio-label">Your first visit</p><h2>Take the short route.</h2>{[["/portfolio", "Meet the engineer", "Experience, projects, and the work behind them."], ["/blogs", "Read an engineering note", "A closer look at decisions, trade-offs, and results."], ["/active-builds", "See what’s in progress", "Current builds and how they work."]].map(([href,title,note],index)=><a href={href} key={href}><span className="wayfinder-number">0{index+1}</span><div><strong>{title}</strong><small>{note}</small></div><span aria-hidden="true">↗</span></a>)}</nav>
      </header>
      <section className="studio-section" aria-labelledby="wayfinder-directory-title"><div className="studio-section-heading"><div><p className="studio-label">Find your way</p><h2 id="wayfinder-directory-title">Follow your curiosity.</h2></div><span className="wayfinder-caption">The site, in three chapters.</span></div><div className="wayfinder-directory">{directory.map((group,index)=><nav aria-label={group.title} key={group.title}><p className="studio-label">0{index+1}</p><h3>{group.title}</h3><p className="wayfinder-group-note">{group.note}</p>{group.links.map(([href,label])=><a href={href} key={href}><span>{label}</span><span aria-hidden="true">↗</span></a>)}</nav>)}</div></section>
      <section className="studio-section wayfinder-updates" aria-labelledby="wayfinder-updates-title"><div className="studio-section-heading"><div><p className="studio-label">Recently added</p><h2 id="wayfinder-updates-title">Worth another look.</h2></div><a className="studio-text-link" href="/whats-new">All updates <span aria-hidden="true">↗</span></a></div>{updates.length ? <div>{updates.map(update=><a className="wayfinder-update" href={update.href} key={`${update.date}-${update.title}`}><time dateTime={update.date}>{update.dateLabel}</time><div><small>{update.category}</small><h3>{update.title}</h3></div><span aria-hidden="true">↗</span></a>)}</div> : <p className="wayfinder-empty">No additions in the last 30 days. Explore the directory above or catch up on earlier updates.</p>}</section>
      <aside className="wayfinder-footer"><div><h2>Stay curious. Stay in touch.</h2><p>New engineering notes and useful updates, occasionally.</p></div><a className="studio-text-link" href="#newsletter">Get updates <span aria-hidden="true">↗</span></a></aside>
    </main></>;
}
